### ISSUE TITLE
max_length error

### ISSUE THREAD

**Issue by Guest007** [caioariede/django-location-field#45] opened 2016-01-27 09:40 UTC
Django 1.9.1
```
from location_field.models.plain import PlainLocationField
...
city = models.ForeignKey(City, blank=True, null=True)
region = models.ForeignKey(Region, blank=True, null=True)
location = PlainLocationField('place',
                             based_fields=['city'],
                             zoom=7
                             )
```
When I try to makemigrations I'm got:
```
ERRORS:
trips.TripExpence.location: (fields.E121) 'max_length' must be a positive integer.
```

Second question:
Name of city defined in another model and linked through ForeignKey. Is this will work?

And third:
Can I set the place for location field using both entites: city and region?

**Comment by caioariede** [comment] 2016-01-27 13:11
The `max_length` thing seems to be a bug. I'll try to confirm later.

Second, the `based_fields` will look for the rendered HTML input field for the fields you set. Usually, for a `ForeignKey` it's a `<select>`, so it will use the value of the selected `<option>`.

Lastly, yes. You can set `based_fields=['city', 'region']`. You can even pass the `suffix` parameter if you want to restrict your search to a specific country, for example: `suffix='Country name'`.

**Comment by caioariede** [comment] 2016-01-27 13:13
And just to mention, the version `2.0` will be out within the next days. I'd consider using it for now.

**Comment by Guest007** [comment] 2016-01-27 13:34
Thank you!
Some addition to error's description:
DB - Postgresql
if I try to add  max_length to the field - I've got error:
```
TypeError: __init__() got multiple values for argument 'max_length'
```

**Comment by caioariede** [comment] 2016-01-27 23:23
I can't reproduce this issue. Which version are you using?

**Comment by Guest007** [comment] 2016-01-28 03:53
python 3.5.0
Django==1.9.1
django-location-field==1.6.1

**Comment by caioariede** [comment] 2016-03-03 20:02
Closing this for now as we released a new version. Please reopen if it persists.

**Closed by caioariede** 2016-03-03 20:02 UTC
